language: node_js

matrix:
  include:
    - node_js: '6.2'
    - node_js: '8.9'
    - node_js: '10.6'
    - node_js: '10.6'
      env:
        - DISABLE_TESTS=true
        - LINTING=true

sudo: false

install:
  - travis_retry npm install

script:
  - if [[ -z "$DISABLE_TESTS" ]]; then npm run test; fi
  - if [[ ! -z "$DISABLE_TESTS" && ! -z "$LINTING" ]]; then npm run lint; fi

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
