language: node_js

matrix:
  include:
    - node_js: 10
    - node_is: 12
    - node_js: 12
      env:
        - DISABLE_TESTS=true
        - LINTING=true

sudo: false

install:
  - travis_retry npm install
  - npm install -g codecov

script:
  - if [[ -z "$DISABLE_TESTS" ]]; then npm run coverage; fi
  - if [[ ! -z "$DISABLE_TESTS" && ! -z "$LINTING" ]]; then npm run lint; fi

after_success:
  - codecov
  - rm -rf ./.nyc_output
  - rm -rf ./coverage
